name: mai2_revive
description: "maimai logout"
publish_to: 'none'
version: 0.2.2

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  crypto: ^3.0.3
  dynamic_color: ^1.7.0
  easy_refresh: ^3.3.5+1
  encrypt: ^5.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.6.6
  get_storage: ^2.1.1
  image_picker: ^1.1.0
  mobile_scanner: ^5.0.1
  oktoast: ^3.4.0
  wakelock: ^0.6.2
  path_provider: ^2.0.7
  http: ^0.13.4
  xml: ^6.0.1
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/MusicList.json
    - assets/LoginBonusSort.xml
    - assets/mai_music_data.json